[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.79.1"
HUGO_THEME = "repo"

[[redirects]] 
from = “/*” to = “/index.html” status = 200

[context.deploy-preview]
command = "cd exampleSite &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"